### ISSUE TITLE
creating certification problem

### ISSUE THREAD

**Issue by teminvictus** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#121]
Today I updated to the latest jrcs/letsencrypt-nginx-proxy-companion version.
But running into problems with the letsencrypt certificates, see code attached. nginx itself works fine.

```
Debugging tips: -v improves output verbosity. Help is available under --help.
/app
/etc/nginx/certs/xxx.xxx.xxx /app
Creating/renewal xxx.xxx.xxx certificates... (xxx.xxx.xxx)
2019-01-11 13:49:54,147:INFO:simp_le:1382: Generating new account key
Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1584, in main
      return main_with_exceptions(cli_args)
   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions
      persist_new_data(args, existing_data)
   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1457, in persist_new_data
      client = registered_client(args, existing_data.account_key)
   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1395, in registered_client
      client = acme_client.Client(directory=args.server, key=key, net=net)
   File "/usr/lib/python2.7/site-packages/acme/client.py", line 257, in __init__
      net.get(directory).json())
   File "/usr/lib/python2.7/site-packages/acme/client.py", line 1152, in get
      self._send_request('GET', url, **kwargs), content_type=content_type)
   File "/usr/lib/python2.7/site-packages/acme/client.py", line 1101, in _send_request
      response = self.session.request(method, url, *args, **kwargs)
   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
      resp = self.send(prep, **send_kwargs)
   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
      r = adapter.send(request, **kwargs)
   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
      aise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7feb84362290>: Failed to establish a new connection: [Errno -3] Try again',))


Unhandled error has happened, traceback is above
```

any ideas?

thanks

**Comment by pgassmann** [comment]
The python code cannot connect to https://acme-v01.api.letsencrypt.org/directory 

Do you have some Firewall-rules restricting outgoing connections or a required http proxy?

**Comment by teminvictus** [comment]
Oh perfect thanks.
Forgot to make a permanent change to my firewall, so after restart it closed docker down again.

solved.
