### ISSUE TITLE
Load balancer to multiple containers of same app

### ISSUE THREAD

**Issue by maufonfa** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#163]
Hi,

I want to know if I can do the following with this?
nginx_proxy (Also load_balancer)
|_website1_container1
|_website1_container2
|_website1_container3
|_website2_container1
|_website2_container2
|_website2_container3

If it's possible how can I achieve it?

**Comment by maufonfa** [comment]
@evertramos Thanks. Also, how can make this work behind a proxy? I already try to embed it in the docker-compose.yml under enviroment, and also in the .conf file for docker.

I obtain the following:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    self._prepare_proxy(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 807, in _prepare_proxy
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 316, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7ff5952486d8>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff5952486d8>: Failed to establish a new connection: [Errno -3] Try again',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/simp_le.py", line 1583, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python3.6/site-packages/simp_le.py", line 1567, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python3.6/site-packages/simp_le.py", line 1457, in persist_new_data
    client = registered_client(args, existing_data.account_key)
  File "/usr/lib/python3.6/site-packages/simp_le.py", line 1395, in registered_client
    client = acme_client.Client(directory=args.server, key=key, net=net)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 274, in __init__
    net.get(directory).json())
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 1168, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python3.6/site-packages/acme/client.py", line 1117, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff5952486d8>: Failed to establish a new connection: [Errno -3] Try again',)))

**Comment by evertramos** [comment]
@maufonfa 

I quiet did not understand what you trying to run behind a proxy.... to run loadbalancer you should look to traefik with kubernetes... you will be fine with that I think.
