### ISSUE TITLE
Error using the test_start-scripts

### ISSUE THREAD

**Issue by laenan8466** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#192]
# Error description:
`502 Bad Gateway` Error occurs on URL after running `sudo ./test_start.sh sub.domain.tld`. The `test_start_ssl.sh`-script is behaving identical. I have the feeling, it could be s.th. very stupid on my side.

# Steps to reproduce

* Clone the repository
* Change external access interface to external IP-adress of the server in the `.env` file (see blow).
```
#
# docker-compose-letsencrypt-nginx-proxy-companion
#
# A Web Proxy using docker with NGINX and Let's Encrypt
# Using the great community docker-gen, nginx-proxy and docker-letsencrypt-nginx-proxy-companion
#
# This is the .env file to set up your webproxy enviornment

#
# Your local containers NAME
#
NGINX_WEB=nginx-web
DOCKER_GEN=nginx-gen
LETS_ENCRYPT=nginx-letsencrypt

#
# Set the IP address of the external access Interface
#
IP=xxx.xxx.xxx.xxx

#
# Default Network
#
NETWORK=webproxy

# If you want to customize the created network, use the following variable
#NETWORK_OPTIONS="--opt encrypted=true"

#
# Service Network (Optional)
#
# In case you decide to add a new network to your services containers you can set this
# network as a SERVICE_NETWORK
#
# [WARNING] This setting was built to use our `start.sh` script or in that special case
#           you could use the docker-composer with our multiple network option, as of:
#           `docker-compose -f docker-compose-multiple-networks.yml up -d`
#
#SERVICE_NETWORK=webservices

# If you want to customize the created network, use the following variable
#SERVICE_NETWORK_OPTIONS="--opt encrypted=true"

#
## NGINX file path (mount into the host)
# Here you can configure the path where nginx stores all the configurations and certificates.
# With the value ./nginx-data it creates a new sub-folder into your current path.

NGINX_FILES_PATH=./nginx-data

#
# NGINX use special conf files
#
# In case you want to add some special configuration to your NGINX Web Proxy you could
# add your files to ./conf.d/ folder as of sample file 'uploadsize.conf'
#
# [WARNING] This setting was built to use our `start.sh`.
#
# [WARNING] Once you set this options to true all your files will be copied to data
#           folder (./data/conf.d). If you decide to remove this special configuration
#           you must delete your files from data folder ./data/conf.d.
#
#USE_NGINX_CONF_FILES=true

#
# Docker Logging Config
#
# This section offers two options max-size and max-file, which follow the docker documentation
# as follow:
#
# logging:
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"
#
NGINX_WEB_LOG_DRIVER=json-file
NGINX_WEB_LOG_MAX_SIZE=4m
NGINX_WEB_LOG_MAX_FILE=10

NGINX_GEN_LOG_DRIVER=json-file
NGINX_GEN_LOG_MAX_SIZE=2m
NGINX_GEN_LOG_MAX_FILE=10

NGINX_LETSENCRYPT_LOG_DRIVER=json-file
NGINX_LETSENCRYPT_LOG_MAX_SIZE=2m
NGINX_LETSENCRYPT_LOG_MAX_FILE=10

#
# Set the local exposed ports for http and https on the Host
#
# NOTE: The default values are 80 and 443, only change this options if you really know what you are doing
#
#DOCKER_HTTP=80
#DOCKER_HTTPS=443
```

* run `sudo ./start.sh`
* run `sudo ./test_start.sh sub.domain.tld`
* To retrieve Error log: `sudo docker logs nginx-letsencrypt`

# Expected result
No `502` error on page, when visiting in Browser.

# Error result
Besides `502` error in browser, the log shows:

```
Info: Custom Diffie-Hellman group found, generation skipped.
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container 2f7ef7a238239d0474b6c23ac6225691e6242c0dcd01dfd991ae9902eae1xxxx)...
2020/02/23 16:22:37 Generated '/app/letsencrypt_service_data' from 3 containers
2020/02/23 16:22:37 Running '/app/signal_le_service'
2020/02/23 16:22:37 Watching docker events
2020/02/23 16:22:37 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
Sleep for 3600s
2020/02/23 16:22:55 Received event start for container 4d30277dxxxx
2020/02/23 16:23:10 Debounce minTimer fired
2020/02/23 16:23:10 Generated '/app/letsencrypt_service_data' from 4 containers
2020/02/23 16:23:10 Running '/app/signal_le_service'
/etc/nginx/certs/sub.domain.tld /app
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container 2f7ef7a238239d0474b6c23ac6225691e6242c0dcd01dfd991ae9902eae1xxxx)...
Creating/renewal sub.domain.tld certificates... (sub.domain.tld)
2020-02-23 16:23:11,708:INFO:simp_le:1323: Generating new account key
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f8bd87fb8d0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8bd87fb8d0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1565, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1549, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1408, in persist_new_data
    args, existing_data.account_key, existing_data.account_reg)
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1341, in registered_client
    directory = messages.Directory.from_json(net.get(args.server).json())
  File "/usr/lib/python3.7/site-packages/acme/client.py", line 1161, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python3.7/site-packages/acme/client.py", line 1110, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8bd87fb8d0>: Failed to establish a new connection: [Errno -3] Try again'))

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
/app
Sleep for 3600s
2020/02/23 16:25:51 Received event die for container 4d30277dxxxx
2020/02/23 16:25:51 Received event stop for container 4d30277dxxxx
2020/02/23 16:26:06 Debounce minTimer fired
2020/02/23 16:26:06 Received event start for container 4c085b5exxxx
2020/02/23 16:26:06 Generated '/app/letsencrypt_service_data' from 4 containers
2020/02/23 16:26:06 Running '/app/signal_le_service'
Sleep for 3600s
2020/02/23 16:26:21 Debounce minTimer fired
2020/02/23 16:26:21 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2020/02/23 16:34:58 Received event die for container 4c085b5exxxx
2020/02/23 16:34:58 Received event stop for container 4c085b5exxxx
2020/02/23 16:35:13 Debounce minTimer fired
2020/02/23 16:35:13 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
2020/02/23 16:35:17 Received event start for container a9c96955xxxx
2020/02/23 16:35:32 Debounce minTimer fired
2020/02/23 16:35:32 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
```

# Comments
* DNS record is set as A-level record to subdomain.
* Maybe not to important: Time in logfile differs from system clock
* OS is CentOS 8

Thank you for much appreciated help!

**Comment by evertramos** [comment]
Hello there!

Set in the env file the IP 0.0.0.0 and try again.

**Comment by laenan8466** [comment]
Hey,
already tried this, but to no success. It's resulting in the identical error.
Cheers,
Laenan

**Comment by evertramos** [comment]
Is this running on a vpn? Any firewall behind your internet connection? When you ping your domain from your server does it shows the servers up address?

**Comment by laenan8466** [comment]
Hey,

* no VPN running
* It's running on a VPS, so no Firewall in the connection.
* CentOS is the OS, so firewalld and SELinux. On another machine (same config), I have a Letsencrypt Docker Setup running, so not clear to me why not this time. ;-)
* Domain is pingable from the Server as it should. DNS record was normal as well.

Your conclusion is, that there is a problem with the Internet connection from inside the docker-container?

**Comment by evertramos** [comment]
No conclusion yet...
Could you run start.sh script again please and try again?

**Comment by laenan8466** [comment]
Did that, but sadly with no success. (Also deleted the repo and cloned it anew, to avoid any other problems.)
* Stopped with `sudo docker-compose down`
* `sudo ./start.sh` (no reported errors)
* `sudo ./test_start.sh sub.domain.tld`

The most recent log:
```
Info: Custom Diffie-Hellman group found, generation skipped.
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container 92fe45fea51acfad85f977bcd377027152018af8ea2f1a90f612331a119a0b29)...
2020/02/25 11:24:30 Generated '/app/letsencrypt_service_data' from 3 containers
2020/02/25 11:24:30 Running '/app/signal_le_service'
2020/02/25 11:24:31 Watching docker events
2020/02/25 11:24:31 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
Sleep for 3600s
2020/02/25 11:25:16 Received event start for container 3f65b76d081a
2020/02/25 11:25:31 Debounce minTimer fired
2020/02/25 11:25:31 Generated '/app/letsencrypt_service_data' from 4 containers
2020/02/25 11:25:31 Running '/app/signal_le_service'
/etc/nginx/certs/sub.domain.tld /app
Reloading nginx docker-gen (using separate container nginx-gen)...
Reloading nginx (using separate container 92fe45fea51acfad85f977bcd377027152018af8ea2f1a90f612331a119a0b29)...
Creating/renewal sub.domain.tld certificates... (sub.domain.tld)
2020-02-25 11:25:33,552:INFO:simp_le:1323: Generating new account key
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f85ad05e810>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f85ad05e810>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1565, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1549, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1408, in persist_new_data
    args, existing_data.account_key, existing_data.account_reg)
  File "/usr/lib/python3.7/site-packages/simp_le.py", line 1341, in registered_client
    directory = messages.Directory.from_json(net.get(args.server).json())
  File "/usr/lib/python3.7/site-packages/acme/client.py", line 1161, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python3.7/site-packages/acme/client.py", line 1110, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f85ad05e810>: Failed to establish a new connection: [Errno -3] Try again'))

Unhandled error has happened, traceback is above

Debugging tips: -v improves output verbosity. Help is available under --help.
/app
Sleep for 3600s
```

---

Another thing I noticed:

* Couldn't remove the webproxy network with `sudo docker network rm webproxy`. 
* Had to delete the test-web container with `sudo docker rm -fv test-web`.
* Removing webproxy was now possible.
* Running `start.sh` and `start_test_ssl.sh` again didn't worked.

**Comment by evertramos** [comment]
Reading the logs seems there is something wrong with permissions...

Are you running as root? 

What is the docker version?

Try to run as root... just as a test.

**Comment by laenan8466** [comment]
Hey,
Versions are:
`Docker version 19.03.6, build 369ce74a3c`
`docker-compose version 1.25.3, build d4d1b42b`

I ran everything with sudo rights from a user account with root rights.

When running from root, result is identical.

**Comment by evertramos** [comment]
I use it on Debian and Ubuntu but not sure if this is the issue...

**Comment by laenan8466** [comment]
So had the time to install a new OS: Debian 10.

To make it short: Worked out of the box. So unclear to me, what was the problem with CentOS 8, but I will keep it on Debian. The CentOS machine was fresh and used for nothing else than the docker-companion.

I will close this issue, feel free to reopen it.

**Comment by evertramos** [comment]
@laenan8466 thanks for you feedback and attention!
