### ISSUE TITLE
 'NoneType' object has no attribute 'wrapped'

### ISSUE THREAD

**Issue by Naramsim** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#62]
```
2018/04/04 16:25:43 Received event start for container aaf3da298d04
2018/04/04 16:25:58 Debounce minTimer fired
2018/04/04 16:25:58 Generated '/app/letsencrypt_service_data' from 8 containers
2018/04/04 16:25:58 Running '/app/signal_le_service'
/usr/lib/python2.7/site-packages/acme/jose/jwa.py:110: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(self.padding, self.hash)
2018-04-04 16:26:01,395:INFO:simp_le:1479: Generating new certificate private key
2018-04-04 16:26:03,097:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/NauJbVSFVxZ00hja2_8Zx9ceBkZg3qBv4_9lZ6iYwsA
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1584, in main
    return main_with_exceptions(cli_args)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions
    persist_new_data(args, existing_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1489, in persist_new_data
    account_key=client.key, key=None, cert=None, chain=None))
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 1195, in persist_data
    plugin.save(new_data)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 493, in save
    key = self.dump_key(data.key)
  File "/usr/lib/python2.7/site-packages/simp_le.py", line 436, in dump_key
    return OpenSSL.crypto.dump_privatekey(self.typ, data.wrapped).strip()
AttributeError: 'NoneType' object has no attribute 'wrapped'

Unhandled error has happened, traceback is above
```

Always happens when deploying a Node application.  All other 8 containers work normally.

```yml
version: '2'

services:
  app:
    hostname: app
    build: ./backend
    restart: on-failure
    expose:
      - '3000'
    command: sh -c "sleep 5 && npm start"
    working_dir: /app
    volumes:
    - ./backend:/app
    - /app/node_modules
    environment:
      VIRTUAL_HOST: api.example.pw
      LETSENCRYPT_HOST: api.example.pw
      LETSENCRYPT_EMAIL: example@outlook.com
networks:
  default:
    external:
      name: webproxy
```

**Comment by evertramos** [comment]
Sorry my late reply...

Please try to add to your compose file the following:

```bash
   environment:
      [...]
      VIRTUAL_PORT: 3000
```

**Comment by Naramsim** [comment]
Thanks, I already solved.

**Comment by FritzTheBat** [comment]
Hey @Naramsim, how did you end up fixing this issue? Experiencing the same issue right now.

**Comment by Naramsim** [comment]
@FritzTheBat sorry, too much time passed. I suggest you try Traefik instead of this project.

**Comment by FritzTheBat** [comment]
Ok thanks. For me this appears to have resolved itself in the meantime, so the cause was probably outside this repo
